export enum RabbitMQ {
    queue = 'inventory_queue',
}

export enum StoreMSG { 
    CREATE_STORE = 'CREATE_STORE',
    UPDATE_STORE = 'UPDATE_STORE',
    DELETE_STORE = 'DELETE_STORE',
    FIND_STORE = 'FIND_STORE',
    FIND_ALL_STORES = 'FIND_ALL_STORES',
}

export enum StoreProductMSG {
    CREATE_STORE_PRODUCT = 'CREATE_STORE_PRODUCT',
    UPDATE_STORE_PRODUCT = 'UPDATE_STORE_PRODUCT',
    DELETE_STORE_PRODUCT = 'DELETE_STORE_PRODUCT',
    FIND_STORE_PRODUCT = 'FIND_STORE_PRODUCT',
    FIND_ALL_STORE_PRODUCTS = 'FIND_ALL_STORE_PRODUCTS',
}